config/routes.rb
FinalProject::Application.routes.draw do
  get "sessions/new"
  

    resources :users
    resources :sessions, :only => [:new, :create, :destroy]
    resources :microposts, :only => [:create, :destroy]

    match '/signup',  :to => 'users#new'
    match '/signin',  :to => 'sessions#new'
    match '/signout', :to => 'sessions#destroy'
    

    match '/about', :to => 'pages#about'
    match '/profile',   :to => 'pages#profile'
    match '/contacts',    :to => 'pages#contacts'
    match '/calendar', :to => 'pages#calendar'
    match '/discussions',   :to => 'pages#discussions'
   
    
    root :to => "pages#home"

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content

  belongs_to :user
  
  validates :content, :presence => true, :length => { :maximum => 140 }
  validates :user_id, :presence => true
  
   default_scope :order => 'microposts.created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
   attr_accessor :password
   attr_accessible :name, :email, :password, :password_confirmation, :birthday, :phone
   
  has_many :microposts, :dependent => :destroy
  

  
   
   email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   
   validates :name, :presence  => true,
                    :length    => { :maximum => 50 }
   validates :email,:presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
   validates :password, :presence     => true,
                        :confirmation => true,
                        :length       => { :within => 6..40 }
                        
   before_save :encrypt_password
   
   def feed
     # This is preliminary. See Chapter 12 for the full implementation.
     Micropost.where("user_id = ?", id)
   end


   # Return true if the user's password matches the submitted password.
   def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
   end

   def self.authenticate(email, submitted_password)
     user = find_by_email(email)
     return nil  if user.nil?
     return user if user.has_password?(submitted_password)
   end
   
   def self.authenticate_with_salt(id, cookie_salt)
     user = find_by_id(id)
     (user && user.salt == cookie_salt) ? user : nil
   end

   private

     def encrypt_password
       self.salt = make_salt unless has_password?(password)
       self.encrypted_password = encrypt(password)
     end

     def encrypt(string)
       secure_hash("#{salt}--#{string}")
     end

     def make_salt
       secure_hash("#{Time.now.utc}--#{password}")
     end

     def secure_hash(string)
       Digest::SHA2.hexdigest(string)
     end
     

                    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :authenticate, :only => [:create, :destroy]
  before_filter :authorized_user, :only => :destroy
  
  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_path
    else
      @feed_items = []
      render 'pages/home'
    end
  end

   def destroy
       @micropost.destroy
       redirect_back_or root_path
     end

     private

       def authorized_user
         @micropost = current_user.microposts.find_by_id(params[:id])
         redirect_to root_path if @micropost.nil?
       end
   end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
      if signed_in?
        @micropost = Micropost.new
        @feed_items = current_user.feed.paginate(:page => params[:page])
      end
  end

  def profile
    @title = "Profile"
  end

  def contacts
    @title = "Contacts"
  end

  def calendar
    @title = "Calendar"
  end

  def discussions
    @title = "Discussions"
  
  end

  def about
    @about = "About"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @title = "Sign in"
  end
  
  def create
     user = User.authenticate(params[:session][:email],
                              params[:session][:password])
     if user.nil?
       flash.now[:error] = "Invalid email/password combination."
       @title = "Sign in"
       render 'new'
     else
       sign_in user
       redirect_to user
   end
 end
  
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
   before_filter :correct_user, :only => [:edit, :update]
   before_filter :admin_user,   :only => :destroy
    
  
  def index
      @title = "All users"
      @users = User.paginate(:page => params[:page])
    end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page])
    @title = @user.name
  end
  

  
  def new
    @user = User.new
    @title = "Sign up"
  end
  
   def create
      @user = User.new(params[:user])
      if @user.save
        sign_in @user
      #  flash[:success] = "Welcome to the Sample App!"
        redirect_to @user
      else
        @title = "Sign up"
        render 'new'
      end
    end
   
    def edit     
      @title = "Edit user"
    end
  
  
   def update
      @user = User.find(params[:id])
      if @user.update_attributes(params[:user])
        flash[:success] = "Profile updated."
        redirect_to @user
      else
        @title = "Edit user"
        render 'edit'
    end
  end

    def destroy
       User.find(params[:id]).destroy
       flash[:success] = "User destroyed."
       redirect_to users_path
     end
  
  
    private


      
      def correct_user
            @user = User.find(params[:id])
            redirect_to(root_path) unless current_user?(@user)
      end
      def admin_user
         redirect_to(root_path) unless current_user.admin?
       end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def title
    base_title = "Gamma Phi Beta"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
     !current_user.nil?
   end
   
   def sign_out
     cookies.delete(:remember_token)
     self.current_user = nil
   end
   
   def authenticate
     deny_access unless signed_in?
   end
   
   def deny_access
     store_location
     redirect_to signin_path, :notice => "Please sign in to access this page."
   end
   
   def redirect_back_or(default)
       redirect_to(session[:return_to] || default)
       clear_return_to
     end
   
   def current_user?(user)
     user == current_user
   end

   def deny_access
      store_location
     redirect_to signin_path, :notice => "Please sign in to access this page."
   end
   
   def redirect_back_or(default)
     redirect_to(session[:return_to] || default)
     clear_return_to
   end
    
  
  private

      def user_from_remember_token
        User.authenticate_with_salt(*remember_token)
      end

      def remember_token
        cookies.signed[:remember_token] || [nil, nil]
      end
      
      def store_location
        session[:return_to] = request.fullpath
      end

      def clear_return_to
        session[:return_to] = nil
      end
      
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user, options = { :size => 50 })
      gravatar_image_tag(user.email.downcase, :alt => h(user.name),
                                              :class => 'gravatar',
                                              :gravatar => options)
    end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
 	<%= javascript_include_tag :defaults %>
	<%= stylesheet_link_tag 'stylePage', :media => 'screen' %>
    <%= csrf_meta_tag %>
</head>

<body>

		<div id="logo">
						
			<% if signed_in? %>	
			<div id="menu">
				<ul>
			      <li><%= link_to "Home", root_path %></li>
			      <li><%= link_to "Profile", current_user %></li>
			      <li><%= link_to "Contacts", users_path %></li>
			      <li><%= link_to "Calendar", calendar_path %></li>
				  <li><%= link_to "Sign out", signout_path, :method => :delete %></li>

				</ul>
			</div>
		    <% else %>
				<div id="menu">
		    <li><%= link_to "Sign in", signin_path %></li>
				</div>
		    <% end %>
	</div>




	<div id="page">
    <%= yield %>		      
	</div>
	
</body>

<div id="footer">
	<p>Copyright (c) 2011 www.gammaphibeta.com. All rights reserved.</p>
</div>

</html>
<%= debug(params) if Rails.env.development? %>

app/views/microposts/_micropost.html.erb
<tr>
  <td class="micropost">
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    </span>
  </td>
  <% if current_user?(micropost.user) %>
  <td>
    <%= link_to "delete", micropost, :method => :delete,
                                     :confirm => "You sure?",
                                     :title => micropost.content %>
  </td>
  <% end %>
</tr>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamma Phi Beta | About</title>
  </head>
  <body>
   
    <p>
      	Gamma Phi Beta (ΓΦΒ) is an international sorority that was founded on November 11, 1874, at Syracuse University in Syracuse, New York.[2] The term "sorority," meaning sisterhood, was coined for Gamma Phi Beta by Dr. Frank Smalley, a professor at Syracuse University.
		The four founders are Helen M. Dodge, Frances E. Haven, E. Adeline Curtis and Mary A. Bingham. The sorority's international headquarters are located in Centennial, Colorado. Gamma Phi Beta currently has 180,000 initiated members, 173 chartered collegiate chapters and more than 175 alumnae groups across the United States and Canada. Gamma Phi Beta's primary objective is to inspire the highest type of womanhood.
    </p>
  </body>
</html>

app/views/pages/calendar.html.erb
<body>

	<script>
	/*Copyright 1996 - Tomer and Yehuda Shiran
	Feel free to "steal" this code provided that you leave this notice as is.
	Additional examples from the book can be found at http://www.geocities.com/SiliconValley/9000/
	For more information contact Tomer or Yehuda Shiran <yshiran@iil.intel.com>*/

	setCal()

	function getTime() {
	// initialize time-related variables with current time settings
	var now = new Date()
	var hour = now.getHours()
	var minute = now.getMinutes()
	now = null
	var ampm = "" 

	// validate hour values and set value of ampm
	if (hour >= 12) {
	hour -= 12
	ampm = "PM"
	} else
	ampm = "AM"
	hour = (hour == 0) ? 12 : hour

	// add zero digit to a one digit minute
	if (minute < 10)
	minute = "0" + minute // do not parse this number!

	// return time string
	return hour + ":" + minute + " " + ampm
	}

	function leapYear(year) {
	if (year % 4 == 0) // basic rule
	return true // is leap year
	/* else */ // else not needed when statement is "return"
	return false // is not leap year
	}

	function getDays(month, year) {
	// create array to hold number of days in each month
	var ar = new Array(12)
	ar[0] = 31 // January
	ar[1] = (leapYear(year)) ? 29 : 28 // February
	ar[2] = 31 // March
	ar[3] = 30 // April
	ar[4] = 31 // May
	ar[5] = 30 // June
	ar[6] = 31 // July
	ar[7] = 31 // August
	ar[8] = 30 // September
	ar[9] = 31 // October
	ar[10] = 30 // November
	ar[11] = 31 // December

	// return number of days in the specified month (parameter)
	return ar[month]
	}

	function getMonthName(month) {
	// create array to hold name of each month
	var ar = new Array(12)
	ar[0] = "January"
	ar[1] = "February"
	ar[2] = "March"
	ar[3] = "April"
	ar[4] = "May"
	ar[5] = "June"
	ar[6] = "July"
	ar[7] = "August"
	ar[8] = "September"
	ar[9] = "October"
	ar[10] = "November"
	ar[11] = "December"

	// return name of specified month (parameter)
	return ar[month]
	}

	function setCal() {
	// standard time attributes
	var now = new Date()
	var year = now.getYear()
	if (year < 1000)
	year+=1900
	var month = now.getMonth()
	var monthName = getMonthName(month)
	var date = now.getDate()
	now = null

	// create instance of first day of month, and extract the day on which it occurs
	var firstDayInstance = new Date(year, month, 1)
	var firstDay = firstDayInstance.getDay()
	firstDayInstance = null

	// number of days in current month
	var days = getDays(month, year)

	// call function to draw calendar
	drawCal(firstDay + 1, days, date, monthName, year)
	}

	function drawCal(firstDay, lastDate, date, monthName, year) {
	// constant table settings
	var headerHeight = 90 // height of the table's header cell
	var border = 4 // 3D height of table's border
	var cellspacing = 10 // width of table's border
	var headerColor = "grey" // color of table's header
	var headerSize = "+3" // size of tables header font
	var colWidth = 100 // width of columns in table
	var dayCellHeight = 25 // height of cells containing days of the week
	var dayColor = "brown" // color of font representing week days
	var cellHeight = 80 // height of cells representing dates in the calendar
	var todayColor = "pink" // color specifying today's date in the calendar
	var timeColor = "brown" // color of font representing current time

	// create basic table structure
	var text = "" // initialize accumulative variable to empty string
	text += '<CENTER>'
	text += '<TABLE BORDER=' + border + ' CELLSPACING=' + cellspacing + '>' // table settings
	text += '<TH COLSPAN=7 HEIGHT=' + headerHeight + '>' // create table header cell
	text += '<FONT COLOR="' + headerColor + '" SIZE=' + headerSize + '>' // set font for table header
	text += monthName + ' ' + year 
	text += '</FONT>' // close table header's font settings
	text += '</TH>' // close header cell

	// variables to hold constant settings
	var openCol = '<TD WIDTH=' + colWidth + ' HEIGHT=' + dayCellHeight + '>'
	openCol += '<FONT COLOR="' + dayColor + '">'
	var closeCol = '</FONT></TD>'

	// create array of abbreviated day names
	var weekDay = new Array(7)
	weekDay[0] = "Sunday"
	weekDay[1] = "Monday"
	weekDay[2] = "Tuesday"
	weekDay[3] = "Wednesday"
	weekDay[4] = "Thursday"
	weekDay[5] = "Friday"
	weekDay[6] = "Saturday"

	// create first row of table to set column width and specify week day
	text += '<TR ALIGN="center" VALIGN="center">'
	for (var dayNum = 0; dayNum < 7; ++dayNum) {
	text += openCol + weekDay[dayNum] + closeCol 
	}
	text += '</TR>'

	// declaration and initialization of two variables to help with tables
	var digit = 1
	var curCell = 1

	for (var row = 1; row <= Math.ceil((lastDate + firstDay - 1) / 7); ++row) {
	text += '<TR ALIGN="right" VALIGN="top">'
	for (var col = 1; col <= 7; ++col) {
	if (digit > lastDate)
	break
	if (curCell < firstDay) {
	text += '<TD></TD>';
	curCell++
	} else {
	if (digit == date) { // current cell represent today's date
	text += '<TD HEIGHT=' + cellHeight + '>'
	text += '<FONT COLOR="' + todayColor + '">'
	text += digit
	text += '</FONT><BR>'
	text += '<FONT COLOR="' + timeColor + '" SIZE=2>'
	text += '<CENTER>' + getTime() + '</CENTER>'
	text += '</FONT>'
	text += '</TD>'
	} else
	text += '<TD HEIGHT=' + cellHeight + '>' + digit + '</TD>'
	digit++
	}
	}
	text += '</TR>'
	}

	// close all basic table tags
	text += '</TABLE>'
	text += '</CENTER>'

	// print accumulative HTML string
	document.write(text) 
	}
	</script>





</body>

app/views/pages/contacts.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamma Phi Beta | Contacts</title>
  </head>
  <body>
    <h1>Contacts</h1>
    <p>
      Contact Ruby on Rails Tutorial about the sample app at the
      <a href="http://railstutorial.org/feedback">feedback page</a>.
    </p>
  </body>
</html>

app/views/pages/discussions.html.erb
<% if signed_in? %>
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="micropost">What's up?</h1>
        <%= render 'shared/micropost_form' %>
 		<%= render 'shared/feed' %>
      </td>
  
    </tr>
  </table>
<% else %>

<% end %>

app/views/pages/home.html.erb
<% if signed_in? %>
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="micropost">What's up?</h1>
        <%= render 'shared/micropost_form' %>
    <%= render 'shared/feed' %>
      </td>
	     <img src="images/group.jpg" align="right" alt="" height="320" width="425" />
	 <img src="images/founder.jpg" align="right" alt="" height="320" width="425" />
	
   
    </tr>
  </table>
<% else %>

	<img border="0" src="/images/crest.jpg"  align="middle"  alt="" width="115" height="150" />
  <h1>
	Gamma Phi Beta was founded November 11, 1874, at Syracuse University, in Syracuse, New York.

	</h1>

<p>
	<h1>Flower: Pink Carnation</h1>

	The carnation was named our official flower at Convention 1888. In 1950, members affirmed the color. Carnations have been revered for more than 2,000 years as one of the most longlasting flowers. Many varieties produce a clove-like scent, and the aroma is said to be both uplifting and motivating.
</p>
<p>
<h1>	Colors: Brown and Mode (dark and light brown) </h1>

	The Founders first selected dark and light blue, but after only a few months, they agreed to change the colors in honor of one of their mentors, Dr. John J. Brown. Brown allowed the women to utilize his study at Syracuse University for meetings. At Convention 1887, the decision was affirmed.
</p>
<p>
<h1>Symbol: Crescent Moon</h1>

	Founder Mary A. Bingham contributed the idea of a crescent as part of the badge design. The waxing crescent is a symbol of our ever-growing sisterhood.

	"We . . . must show growth in knowledge, wisdom, power, womanliness year by year or we are not living up to our chosen symbol." Sara Preston Finley (Minnesota-Twin Cities, 1912) 
</p>

<h1>Crest</h1>
<p>
	
	Our crest, or shield, was envisioned by Gertrude Comfort Morrow (California-Berkeley), the winner of a Sorority-wide design contest in 1915. At Convention 1927, delegates affirmed that the crest could only be worn by initiated members who were able to understand and appreciate the ideals within.
  </p>

<% end %>

app/views/pages/profile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamma Phi Beta | My Profile</title>
  </head>
  <body>
    <h1>Contact</h1>
    <p>
      Contact Ruby on Rails Tutorial about the sample app at the
      <a href="http://railstutorial.org/feedback">feedback page</a>.
    </p>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <table class="microposts" summary="User microposts">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </table>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </td>
  <td class="micropost">
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  </td>
  <% if current_user?(feed_item.user) %>
  <td>
    <%= link_to "delete", feed_item, :method => :delete,
                                     :confirm => "You sure?",
                                     :title => feed_item.content %>
  </td>
  <% end %>
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.name %>
    </span>
    <span class="microposts">
      <%= pluralize(current_user.microposts.count, "micropost") %>
    </span>
  </a>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => 30 %>
  <%= link_to user.name, user %>

  <% if current_user.admin? %>
  | <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{user.name}" %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :birthday, "Birthday" %><br />
    <%= f.text_field :birthday %>
  </div><div class="field">
    <%= f.label :phone, "Phone Number" %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/index.html.erb
<img src="images/house.jpg" align="right" alt="" height="650" width="500" />

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
	<%= link_to "Edit Profile", edit_user_path(current_user) %>
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
</h1>
 <p>E-mail:</p><%= @user.email %>
 <p>Birthday:</p><%= @user.birthday %>
 <p>Phone number:</p><%= @user.phone %>

 
      <% unless @user.microposts.empty? %>
        <table class="microposts" summary="User microposts">
          <%= render @microposts %>
        </table>
        <%= will_paginate @microposts %>
      <% end %>



    </td>



  
  </tr>
</table>